<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<body>

<div>Hi ${username},</div><br/>

<div>Thank you for contacting Us.</div><br/>

<div>Your Query on <i>"${query}"</i> will be soon addressed by our experts.</div><br/>

<div>Thanks for your patience!!</div><br/>

<div>Regards,</div>
<div>Team Marketplace</div>

</body>
</html>